version: '3' 
services: 
  prisma: 
    image: prismagraphql/prisma:1.32
    restart: always
    ports: 
    - "4466:4466"
    environment: 
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            user: root
            password: root
            rawAccess: true
            port: 3306
            migrations: true
  mysql: 
    image: mysql:5.7
    restart: always
    ports: 
     - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - mysql:/var/lib/mysql
volumes: 
  mysql: ~
